### ISSUE TITLE
HTTP 403 error while fetching a few helm charts from charts repo

### ISSUE THREAD

**Issue by ankushchadha** [appscode/charts#87]
Hello chart maintainers

There are a few charts on _charts.appscode.com/stable_ that results in HTTP 403 error  -
```
helm repo add appscode https://charts.appscode.com/stable/
helm fetch appscode/stash-mysql --version=8.0.14-beta.20200708
Error: failed to fetch https://charts.appscode.com/testing/stash-mysql/stash-mysql-8.0.14-beta.20200708.tgz: 403 Forbidden
```

The reason is that the index.yaml of the stable repo points to testing

```
➜  ~ curl https://charts.appscode.com/stable/index.yaml | grep stash-mysql
stash-mysql:
    description: stash-mysql - MySQL database plugin for Stash by AppsCode
    name: stash-mysql
    - https://charts.appscode.com/testing/stash-mysql/stash-mysql-8.0.14-beta.20200708.tgz
    description: stash-mysql - MySQL database plugin for Stash by AppsCode
    name: stash-mysql
    - https://charts.appscode.com/testing/stash-mysql/stash-mysql-8.0.3-beta.20200708.tgz
    description: stash-mysql - MySQL database plugin for Stash by AppsCode
    name: stash-mysql
```

This was observed when certain helm charts failed to make it to [ChartCenter](http://chartcenter.io/) due to HTTP 403 error however, other [charts](https://chartcenter.io/appscode/stash?tab=readme) are fine.

Thanks
